<?php

use Illuminate\Database\Seeder;

class QuestionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 6,
            'curriculum_number' => '8-1-1',
            'title' => 'test',
            'remarks' => 'test',
            'question' => '.envファイルとはどのようなファイルなのでしょうか。また、どのような目的で使用されるのでしょうか？',
            'is_resolved' => 0,
            'check' => true,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 6,
            'curriculum_number' => '5-1-1',
            'title' => 'test',
            'remarks' => 'test',
            'question' => 'アプリケーションキーとはなんなのでしょうか？',
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 7,
            'curriculum_number' => '6-1-2',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "DBのユーザーへの権限付与に関して\nGRANT ALL PRIVILEGES ON blog.* to 'dbuser'@'localhost';\nと入力してもエラーが出ます。",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 6,
            'curriculum_number' => '8-2-1',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "blogのアプリケーションを起動しても１つしか投稿が表示されません。\nすでにforeachも使ってループ処理させていますが、解説動画のように２つの表示が出ません。",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 5,
            'curriculum_number' => '4-1-4',
            'title' => 'test',
            'remarks' => 'test',
            'question' => '任意課題について質問です。コマンドライン関数の$argvの使い方がわかりません。'."\nまた、propertyで定義しているのにUndefined variableと出てきてしまう理由がわかりません。",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 6,
            'curriculum_number' => '8-4-1',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "inputタグのplaceholder属性とvalue属性の違いがわからないです。\nまた、oldメソッドついてもよくわからないです。",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 6,
            'curriculum_number' => '5-1-1',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "Laravelアプリケーションの動作確認を行なったところ、「そのようなファイルやディレクトリはありません」と表示されるのですが、どうしたら良いですか？",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 7,
            'curriculum_number' => '6-1-1',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "「MariaDBのインストール」の部分を実行したが、エラーが発生してしまいました。",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 6,
            'curriculum_number' => '5-1-1',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "エラーの意味がわかりません。workフォルダの中身を空にして実行するということですか？",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 1,
            'topic' => 9,
            'curriculum_number' => '成果物',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "Modelとマイグレーションファイルを作成ができません。",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 6,
            'curriculum_number' => '8-2-1',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "DB内のテーブルにupdated_atというカラムが存在しないとのエラーが出ます。",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 6,
            'curriculum_number' => '8-4-1',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "バリデーションエラーメッセージが表示されません。",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 6,
            'curriculum_number' => '5-1-1',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "実行中のアプリケーションのプレビューができません",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 6,
            'curriculum_number' => '8-4-1',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "Google chromeでアプリをプレビューすると【VFS connection does not exist】というエラーが出てしまう。",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 2,
            'curriculum_number' => '2-1-2',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "画像の挿入方法がわかりません。",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 6,
            'curriculum_number' => '8-4-1',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "ルーティングをいじったあと突然404エラーが発生してしまいました。",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 1,
            'curriculum_number' => '2-1-1',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "HTMLファイルを作成しブラウザで開いても、何も表示されません。",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 3,
            'curriculum_number' => '2-1-3',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "ボタンをクリックした後、〇〇が選択されましたと表示するメソッドを実装したいが、エラーが起きる。",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 6,
            'curriculum_number' => '8-2-1',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "検索結果とページネーションを同時に実装したい。",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 4,
            'curriculum_number' => '3-2-1',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "php7.3へのアップデートする際以下の写真のエラーが発生してしまいます",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 4,
            'curriculum_number' => '3-2-1',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "PHP7系Remiリポジトリの優先度設を行いましたが、うまくいきません。",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 7,
            'curriculum_number' => '6-1-1',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "DB設計環境構築においてユーザへの新規データベース権限の付与ができません",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 5,
            'curriculum_number' => '4-1-1',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "php基礎(HelloWorld&データ型)についてうまくいきません。",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 1,
            'topic' => 9,
            'curriculum_number' => '成果物',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "Seederが実行されません。",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 6,
            'curriculum_number' => '8-2-1',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "コントローラー内でモデルに記述されたメソッドが正常に呼び出せません。",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 6,
            'curriculum_number' => '8-2-1',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "課題2の3でhttps://〜〜〜/postsでアクセスした時にindex.blade.phpの画面が表示されるようにするとありますが、解説や動画はhttps://〜〜〜/ にアクセスしています。どちらにすればよいのでしょうか。",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 7,
            'curriculum_number' => '6-1-1',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "Rootユーザーのパスワード変更でパスワード登録までは完了したのですが、画像のようにパスワード再入力するところで文字が入力できなくなってしまいました。",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 8,
            'curriculum_number' => '7-1-1',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "gitをアップデートしてもエラーになってしまいます。",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 6,
            'curriculum_number' => '8-2-1',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "投稿が複数表示されません。",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 6,
            'curriculum_number' => '8-3-1',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "ワイヤーフレーム作成時、下記画像のようにタイトル1をクリックすると別リンクに飛ぶようにするにはどうすれば良いでしょうか。",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 6,
            'curriculum_number' => '8-1-1',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "ブラウザの動作確認が取れません。",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 6,
            'curriculum_number' => '8-4-1',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "ページネーションのリンクをクリックしても遷移できません。またブラウザで開くと「Oops VFS connection….」と表示されてしまいます。",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 6,
            'curriculum_number' => '8-4-1',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "ブログ投稿作成画面がうまく表示されません。",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 6,
            'curriculum_number' => '8-5-1',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "View [posts.edit] not fund と出てページ遷移ができません。",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 7,
            'curriculum_number' => '6-1-1',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "画像を保存するためAWSのクラウドサービスS3を使用していますが、設定がうまくいきません。",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 6,
            'curriculum_number' => '8-6-1',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "deleteボタンを押すと419エラーが発生してしまいます。",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 7,
            'curriculum_number' => '6-1-1',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "突然データベースに接続できなくなってしまいました。",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 6,
            'curriculum_number' => '8-6-1',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "deleteボタンを押すとエラーが出てしまいます。",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 6,
            'curriculum_number' => '5-1-1',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "Laravelが正常に作動しません。",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        DB::table('questions')->insert([
            'category' => 0,
            'topic' => 2,
            'curriculum_number' => '2-1-2',
            'title' => 'test',
            'remarks' => 'test',
            'question' => "cssが読み込めません。",
            'is_resolved' => 0,
            'check' => false,
            'user_id' => 1,
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ]);
        
        // 7月1日以降から
    }
}
